name: Coffe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        repository: XMatrixStudio/Coffee

    - name: Build
      run: /bin/bash build.sh

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: m208/xmatrixstudio-coffee
        tags: latest
        username: m208
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: false
