# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: XMatrixStudio/Violet.Server
        ref: "2.0"
        
    - name: Write a Dockerfile
      run: |
        cat << EOF > Dockerfile
        FROM library/node:10-alpine
        WORKDIR /app
        COPY . /app
        RUN npm install
        CMD ["node", "index.js"]

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: m208/xmatrixstudio-violet-server
        tags: "2.0"
        username: m208
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: false
